---
version: '3.4'
services:
  # feedgen:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   env_file: .env
  #   ports:
  #     - 3000:3000
  redis:
    image: redis:7.2.4-alpine
    ports:
      - 6379:6379
    command: ['redis-server', '/redis.conf']
    volumes:
      - redis_data:/data
      - ./conf/redis.conf:/redis.conf
volumes:
  redis_data:
